### ISSUE TITLE
Retry download when SciHub is unreachable

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#10]
Lately I've had massive issues downloading data via the SciHub due to ESAs Server responding with 502/503 errors. The problem is that this also aborts the complete download session.

Should we implement a logic to retry every 5 to 10 minutes if the SciHub is unreachable? ESA suggests in their [API usage policy](https://scihub.esa.int/news/News00040) to "retry only after a reasonable delay e.g. 5 minutes".

**Comment by willemarcel** [comment]
It could be an option, but not the default. I've had a lot of 502 errors during the day, but I programed my downloads to the night and it is working well.

**Comment by Fernerkundung** [comment]
This issue  is solved in #13
