### ISSUE TITLE
Change in SciHub API location

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#12]
Looks like ESA is trying to limit the amount of data downloaded through the API.

- "API Hub is dedicated to users of the scripting interface. The API Hub Access is currently available only for users **registered before the 20th of November** 12:00 UTC, the user credentials as of the 20th November are valid to access this site."

- new URLs for search and download: [https://scihub.esa.int/apihub/](https://scihub.esa.int/apihub/) , [https://scihub.esa.int/apihub/odata/v1](https://scihub.esa.int/apihub/odata/v1)

**Comment by GianniCristian** [comment]
Yeah. Because of this, I guess that the method "get_product_info" needs to be changed. Is it right?

**Comment by willemarcel** [comment]
@GianniCristian I tested right now and the older urls are working with scripts yet.

@Fernerkundung I think we could change to the new url and add a option to define another url as a parameter of SentinelAPI class. What do you think?

**Comment by Fernerkundung** [comment]
@willemarcel I just tested both URLs with my account created prior to 20-11-2015 - both work.

To me it looks like the new urls are a clone of the regular API so they can balance the load better. As they say now on the front page "*All API users regularly downloading the latest S-1 data are encouraged to use this access point for a better performance. *"

I'm +1 on changing to the new API url.

What would be preferable: a command line flag for URL selection or manual entry?

e.g.

`sentinel search --use_api_url_2` or rather `sentinel search --url https://scihub.esa.int/dhus/`

**Comment by willemarcel** [comment]
@Fernerkundung I prefer

    --url https://scihub.esa.int/dhus/

I'll make the changes right now.

**Comment by Fernerkundung** [comment]
@willemarcel Perfect!

Manual URL selection would also solve the next possible issue: It sounds like both APIs will have different lengths of the rolling archive. The new API for instance only has data back to the 16-11-2015, not the full archive.

**Comment by willemarcel** [comment]
I published the version 0.4.3 in Pypi with these changes. Tell me if you find something wrong.
