### ISSUE TITLE
Verify the integrity of the downloaded images

### ISSUE THREAD

**Issue by valgur** [ibamacsr/sentinelsat#15]
Hi,

I really like this utility for its Python and command line interfaces, which I find both to be very clean and well-thought-out. I would love to use it to manage my SciHub downloads but it is currently missing a critical function I need: ensuring that the downloaded images are complete and non-corrupted. Would you consider adding an integrity check after finishing a image download and possibly re-download the image until the check passes successfully (perhaps a limited number of times to prevent an infinite loop)?

Broken downloads are not at all rare in my experience, especially when downloading SLCs. For example, a snippet from a recent downloading session with my personal script:
```
Downloading z:\Sentinel-1a\Latvia\tormimurd\data\S1A_IW_GRDH_1SDV_20141009T160333_20141009T160356_002755_003185_F8C5.zip. Id = c998ec17-c7c6-429f-a2f6-38ff2f26f8f2, Checksum = D317054C7A5E71ADC9EC3A09B85EC15C, Length = 1,576,536,265
0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Downloaded 1576536265/1576536265 bytes, checksum is D317054C7A5E71ADC9EC3A09B85EC15C.
Downloading z:\Sentinel-1a\Latvia\tormimurd\data\S1A_IW_GRDH_1SDV_20141021T160333_20141021T160356_002930_003530_A0B5.zip. Id = 7dd51ac2-3f26-4b4c-9162-8275ece60149, Checksum = 40824789726D8248F6B55EAFF16BF970, Length = 1,575,458,978
0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Downloaded 1575458978/1575458978 bytes, checksum is 40824789726D8248F6B55EAFF16BF970.
Downloading z:\Sentinel-1a\Latvia\tormimurd\data\S1A_IW_GRDH_1SDV_20141023T043423_20141023T043448_002952_0035AA_6B85.zip. Id = 427d77d8-9f81-467a-b2a8-e96eae7c36d2, Checksum = C9F1FC5D8B90A8F1126997FA85626CAD, Length = 1,763,514,174
0%....10%....20%....
Downloaded 517355836/1763514174 bytes, checksum is E8A7A9F251199A06DA6FD600A8201C2E.
0%
Downloaded 2718612/1763514174 bytes, checksum is 10E3B673F03AEB28A7945CA57F33ED32.
0%
Downloaded 956/1763514174 bytes, checksum is 001D191BC2EDF21412EB82C3A003FE81.
0%
Downloaded 956/1763514174 bytes, checksum is 001D191BC2EDF21412EB82C3A003FE81.
0%
Downloaded 956/1763514174 bytes, checksum is 001D191BC2EDF21412EB82C3A003FE81.
0%..
```

SciHub product query responses include an MD5 checksum along with its other information, which can be used to test the file's integrity. Alternatively, since the products are always ZIP-files, https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.testzip should work as well.

If it's of any use, I have uploaded the current script I use for downloading from SciHub with a checksum test as a Gist here: https://gist.github.com/valgur/3e19ede9dd51e8bc5626
The key parts there are
* downloading with a check: https://gist.github.com/valgur/3e19ede9dd51e8bc5626#file-scihub_downloader-py-L222
* XPath for the checksum: https://gist.github.com/valgur/3e19ede9dd51e8bc5626#file-scihub_downloader-py-L109

I can also volunteer my own time for adding this functionality as well some time in December, if necessary.

Best regards,
Martin

**Comment by Fernerkundung** [comment]
This would be a great addition but I'm a bit worried about the performance if the checksum is calculated *after* download.

The faster way would be to calculate the checksum parts as the file is downloaded. I'm not sure however if that can be implemented with homura.

**Comment by valgur** [comment]
I agree, that would definitely be the preferred method. I was not sure about homura's capabilities in that regard either, which is why I suggested the after downloading approach.

I took a closer look at homura now and the `pass_through_opts` parameter in conjunction with cURL's [`WRITEFUNCTION`](http://pycurl.sourceforge.net/doc/callbacks.html#WRITEFUNCTION) callback (maybe WRITEDATA as well) seemed promising initially. I did some testing and that approach fails, though, because it also overrides homura's callback that writes the downloaded data to a file. I suppose you could add writing to the target file in the new callback as well, but that seems kind of silly.

Maybe scrap homura altogether? The functionality it seems to mostly provide besides being a convenient wrapper around pycurl are the progressbar and continuing/repeating of interrupted downloads. Adding these on top of the requests library, which is much more python-friendly imo, should not be too difficult.

**Comment by valgur** [comment]
I expanded my downloading script a bit and pushed it to a separate repo now (https://github.com/valgur/SciHub_downloader). That itself is not all that important, but what I learned by implementing a correct method of continuing any interrupted downloads instead of restarting them is that simply correctly resuming the downloads (like homura does) takes care of almost all of the integrity problems and downloading headaches in general that I was complaining about earlier.

So I guess adding a checksum verification is not something as urgent as I initially made out to be after all.
Would be nice to have, nevertheless, of course. :-)

**Comment by Fernerkundung** [comment]
@valgur 

Thank you for gathering that information. I'm currently running tests if the checksum calculation is necessary and the zip file integrity check might be faster.

Homura still doesn't take care of one thing: The SciHub Server going down/into maintenance mid-download. As it turns out this is also quite complicated to test/mock.

Nice script. May I suggest also adding the second API url: https://scihub.esa.int/apihub/
While it does not contain the same amount of data as the old-API (yet) it has proven to be a lot more stable over the last few days.

**Comment by Fernerkundung** [comment]
I included a checksum test after downloading with #16 

This is done after each download and produces a negligible performance degradation (on my system +3 seconds for the MD5 calculation).

Creating a list of the checksums isn't as straightforward as i hoped. The scihub search protocol does not return the checksums. These are only included in the query for each product. Since the scihub is having massive performance issues as is I would chose not to stress it further.

Testing a number of already downloaded scenes is best done with testzip, as already proposed.

I have to add though that I tested the resume functionality of homura to the extreme in the last days: Interrupting a download, waiting 2 days and continueing it with a different username and to a different location to where I moved the file. So far I have not had any corrupt files.

**Comment by JohnLM** [comment]
Hey guys!
I've looked into this, and I've noticed a piece of XML code injected into the file whenever connection was lost. This is likely an error message dumped by proxy managing traffic for Scihub servers.
Notably this happens in-band with data and not just HTTP errors. As this is embedded in the data stream, resuming from the end of the partial file will leave the XML garbage in the file, effectively overwriting the relevant piece of data.

My solution: resume with rollback! Discard some data at the end of interrupted download. The XML garbage was around 150 bytes.

Unfortunately, this not easily overriden in homura, so I myself resorted using pycurl directly. But perhaps bringing the retry code in sentinelsat and truncating file before resuming would work.

**Comment by Fernerkundung** [comment]
@JohnLM Thanks for the heads up.

Did you find any form of documentation by ESA which would allow us to make sure how far we have to roll back?

So far we can't be sure what ESA will change/do next so it seems to me the best option would be to err on the safe side and not resume downloads at all but delete the partial file and start them fresh.

**Comment by valgur** [comment]
Hmm... could adding [FAILONERROR](http://curl.haxx.se/libcurl/c/CURLOPT_FAILONERROR.html) cURL option to homura perhaps work? I have been intending to test this issue specifically on homura but have not gotten around to it yet, because the setup for that would be somewhat elaborate.

I think I used to have the same problem in the script I am currently using ([valgur/SciHub_downloader](https://github.com/valgur/SciHub_downloader)) until I added a check for HTTP status >= 400 errors and forced the download restart (and resume) in such case ([this bit of code, to be specific](https://github.com/valgur/SciHub_downloader/blob/master/SciHub_downloader.py#L125)). After this, I have not had any resumed downloads result in a corrupted file. Even during the past week, where the SciHub has been dropping every download at least once, it seems.

**Comment by JohnLM** [comment]
@Fernerkundung No, I haven't come across any documentation on that. I use rollback of 1024 bytes which covers the ~150 byte XML garbage (and also output of HTTP 4xx errors, btw).
I've also had idea of checking .zip file integrity during download, somewhat similarly you've discussed above. But it is not that straightforward.
Always starting fresh is the safest way, but I can almost never download those 4GB product .zips in one go.

@valgur FAILONERROR won't work for garbage when connection is dropped where HTTP 4xx never gets returned (headers were already returned when download started). pycurl raises error with pycurl.E_PARTIAL_FILE error number in this case, with the garbage already written at the end of file.
FAILONERROR should work though when you start fresh download but the server is busy.

**Comment by pominville** [comment]
Are there still any plans on implementing the checksum functionality for use with Python?

**Comment by Fernerkundung** [comment]
@pominville there is in the [download method](https://github.com/ibamacsr/sentinelsat/blob/751cb06a4d1a3f06cac4f1e850e2469be6fc325f/sentinelsat/sentinel.py#L222).

Just use `api.download(checksum=True)`.

I discarded the idea of including a download with rollback as ESA is changing the Scihub behaviour often and most of the times without prior notice.

**Comment by pominville** [comment]
ok thanks, I will test as soon as ESA servers are back online on Monday...

**Comment by Fernerkundung** [comment]
Following the [update of scihubs resume functionality](https://scihub.copernicus.eu/news/News00080) I've seen less and less corrupt downloads after a resume.

In combination with the implemented checksum test I think this issue can be closed.

**Comment by valgur** [comment]
This can be definitely closed now, I agree. Should be pretty reliable.
