### ISSUE TITLE
adding Travis CI

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#17]
@willemarcel How is your stance on adding a Travis CI hook to this project?

I think as it continues to grow automated testing of new functions/refactoring for Python 2/3 should make the testing/merging of PRs a lot easier.

I just tested in on my fork and everything seems to work as easy as advertised (regarding this was my first time setting up a CI). https://travis-ci.org/Fernerkundung/sentinelsat [![Build Status](https://travis-ci.org/Fernerkundung/sentinelsat.svg?branch=master)](https://travis-ci.org/Fernerkundung/sentinelsat)

**Comment by willemarcel** [comment]
Hi,

I like to use TravisCI, but I don't now how to define the user and password of the SciHub there without letting it public. Have you solved this?

**Comment by Fernerkundung** [comment]
That's easy: You can [encrypt variables with Travis](https://docs.travis-ci.com/user/encryption-keys/). My details are also inside the .Travis.yml under 'secure:'

**Comment by willemarcel** [comment]
Great. Could you make a pull request with the travis.yml?

**Comment by Fernerkundung** [comment]
Travis doesn't allow secure variables to be used across forks for security reasons.

To include new secure variables into the travis.yml one needs to have write access to the repo (as far as I understand).

So I can make a PR, but it won't work unless you grant me write access to the repo or change the included secured variables yourself. :)

**Comment by willemarcel** [comment]
Ok, I'll change the secured variables.

**Comment by Fernerkundung** [comment]
The setup that works with Travis is outlined in #20.
You only need to replace the encrypted variables and register the repo on Travis.

**Comment by willemarcel** [comment]
solved! Thanks!
