### ISSUE TITLE
Sentinel-2 support

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#18]
As of a few hours ago the pre-operational Sentinel-2 hub went live. Luckily the biggest change I can spot so far is the new url (which is already covered with the -u parameter) and some differences in returned metadata.

I think access to Sentinel-2 should be included in 'sentinelsat', especially as it doesn't require a lot of refactoring.

What I tested so far:

- you have to use 'https://scihub.esa.int/s2/' instead of 'https://scihub.copernicus.eu/s2' for the time being or you get a certificate error
- 'sentinel search' and 'sentinel download' behave as expected and I am currently downloading S-2 scenes with it

**Comment by willemarcel** [comment]
I'll need to download Sentinel-2 data soon. We can work to totally support Sentine-2 in sentinelsat.

**Comment by Fernerkundung** [comment]
I'm currently in the midst of writing tests and testing Sentinel-2 support.

@willemarcel Should we expose the Satellite selection and cloud cover in the CLI with their own flags or depend on the user formulating the query terms?

I was thinking something like:

`sentinel search -sentinel2 -cc 30 <user> <password> <geojson>`

This would produce the same result as:

`sentinel search -q "platformname=Sentinel-2,cloudcoverpercentage=[0 TO 30]" <user> <password> <geojson>"

or from Python:

`api.query(platformname="Sentinel-2", cloudcoverpercentage="[0 TO 30]"`

**Comment by vincentsarago** [comment]
hi @Fernerkundung 
Setting the maximum cloud cover seems to be a nice solution (same as landsat-util, https://pythonhosted.org/landsat-util/commands.html) 

Great work,

Vincent

**Comment by Fernerkundung** [comment]
as per #24

- search, parsing and download of Sentinel-2 images works in API and CLI
- CLI has new flags (`-c` for maximum cloud cover, `--sentinel2` and `--sentinel1` to limit search to one constellation)
