### ISSUE TITLE
scihub domain changes

### ISSUE THREAD

**Issue by fradaloisio** [ibamacsr/sentinelsat#19]
This morning the Scientific Data Hub changes domain and becomes https://scihub.copernicus.eu instead of https://scihub.esa.int .
https://scihub.copernicus.eu/news/News00047
All the request will be rewriting, have you some problems for download the data?

**Comment by willemarcel** [comment]
I'm working on update sentinelsat to the new domain. I'll publish another version in some minutes

**Comment by willemarcel** [comment]
Published the version 0.5.1 on Pypi with the new domain URL.
