### ISSUE TITLE
S2: download tiles

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#28]
Sentinel-2 data is tiled according to the Military Grid Reference System (MGRS).

At the moment `sentinelsat` only allows the download of complete S2 _products_ which contain a number of _tiles_.

It would be nice to have the option to search and download data for a specific tile (or a number of tilkes) only.

@olivierhagolle already implemented something similar in his [sentinel_download.py](https://github.com/olivierhagolle/Sentinel-download/blob/4230c5a826384e2a6b17ad8db09f6f0fdefbb16a/Sentinel_download.py#L231).

**Comment by willemarcel** [comment]
Hi @Fernerkundung,

I'm not working with sentinel right now, but it would be really nice to have that feature.

**Comment by Fernerkundung** [comment]
Hi @willemarcel 
I'm currently working on a tiled download, but with my available time it might be a while until it's ready.
Slightly OT: Even when you are not working with Sentinel data, will you still be maintaining this library, merging PRs etc.?

**Comment by willemarcel** [comment]
Yes, I can mantain the repository, merge the PRs and publish the new versions to Pypi

**Comment by benboughton1** [comment]
Interested in this one too.

**Comment by Fernerkundung** [comment]
By early September 2016 the products will be [provided as single tiles](https://scihub.copernicus.eu/news/News00092) by the SciHub. This would solve the tiled download issue but possibly require some refactoring to deal with changes in the [Sentinel-2 product specification](https://sentinels.copernicus.eu/documents/247904/685211/Sentinel-2-Products-Specification-Document-Draft).

I'll close this issue in the meantime as it will be solved by the changes and new problems are better suited to be their own issues.
