### ISSUE TITLE
Download doesn't work anymore

### ISSUE THREAD

**Issue by unnic** [ibamacsr/sentinelsat#29]
Hello,

I've used your code and it worked very well until recently.
Now the products are found from my query but the downloaded file is just a faulty 276 byte .zip file. The download finsihes without error.

After updating all python packages (via pip) i get the following errors when a product is found and attempted to download (no error when no product):

```
Traceback (most recent call last):

  File "c:\anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)

  File "c:\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals

  File "C:\Anaconda2\Scripts\sentinel.exe\__main__.py", line 9, in <module>
  File "c:\anaconda2\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)

  File "c:\anaconda2\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)

  File "c:\anaconda2\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "c:\anaconda2\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "c:\anaconda2\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)

  File "c:\anaconda2\lib\site-packages\sentinelsat\scripts\cli.py", line 97, in search
    api.download_all(path)

  File "c:\anaconda2\lib\site-packages\sentinelsat\sentinel.py", line 270, in download_all
    self.download(product['id'], path, checksum, **kwargs)

  File "c:\anaconda2\lib\site-packages\sentinelsat\sentinel.py", line 251, in download
    download(product['url'], path=path, session=self.session, **kwargs)

  File "c:\anaconda2\lib\site-packages\homura-0.1.3-py2.7.egg\homura.py", line 274, in download
    hm.start()

  File "c:\anaconda2\lib\site-packages\homura-0.1.3-py2.7.egg\homura.py", line 196, in start
    raise e

pycurl.error: (60, 'SSL certificate problem: self signed certificate in certificate chain')
```

**Comment by Fernerkundung** [comment]
This is an issue with `pycurl` , not `sentinelsat` - just tested and the query/download works fine.

You can likely solve the issue with `conda install pycurl pyopenssl`.

**Comment by unnic** [comment]
Thanks for your input. I added pyopenssl but the same problems remain (faulty .zip on not updated machine/error on updated one). I also uninstalled/reinstalled sentinelsat and pycurl to no avail.
I'd be very thankful if you can help me out, your script became an integral part of my processing routine.

**Comment by Fernerkundung** [comment]
I just tested this again on Win7_x64 using conda.

```
conda install pycurl pyopenssl requests
pip install sentinelsat
```

Everything works without SSL errors on https://scihub.copernicus.eu/dhus, https://scihub.copernicus.eu/apihub and https://scihub.copernicus.eu/s2.

Here is the minimal working conda environment yml. I imported this on 4 other Windows machines and no SSL errors occured. Are you absolutely certain you installed/updated `pycurl` and `pyopenssl` through conda and not pip?

```yaml
name: C:\Miniconda3\envs\sensat
dependencies:
- cffi=1.5.2=py27_0
- cryptography=1.0.2=py27_0
- curl=7.45.0=vc9_1
- enum34=1.1.2=py27_0
- idna=2.0=py27_0
- ipaddress=1.0.14=py27_0
- msvc_runtime=1.0.1=vc9_0
- pip=8.1.0=py27_0
- pyasn1=0.1.9=py27_0
- pycparser=2.14=py27_0
- pycurl=7.19.5.3=py27_1
- pyopenssl=0.15.1=py27_1
- python=2.7.11=2
- requests=2.9.1=py27_0
- setuptools=20.2.2=py27_0
- six=1.10.0=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=vc9_2
- pip:
  - click==6.3
  - geojson==1.3.2
  - homura==0.1.3
  - humanize==0.5.1
  - sentinelsat==0.6.4
```

**Comment by unnic** [comment]
Yes, I installed everything as specified on this page. It did work until a few days ago until one day the download resulted in faulty .zip files only. This happend at the same time on both machines, independently of each other so I assumed something in the sentinel API changed. The SSL errors occured after I updated pip and all python packages. 

I did a full re-installation of Python/Anaconda, pycurl and sentinelsat. Now its back at generating faulty 276 byte files with no error. Win_10x64.

thanks for your help.

**Comment by Fernerkundung** [comment]
Which API are you downloading from, `dhus`, `apihub` or `s2`? Can you provide a scene-id of one of the scenes that is faulty?

I tried reproducing this issue in Win7_x64, Win10_x64 and OsX but get no issues whatsoever when using a fresh conda environment.

Have you tried downloading from another https source with pycurl? I suspect the issue is either with your pycurl installation or your network, which might block these connections to some extent.

**Comment by unnic** [comment]
- apihub

- Any scene I attempt to download is faulty, e.g: S2A_OPER_PRD_MSIL1C_PDMC_20160319T130845_R079_V20150807T095007_20150807T095007 

- I don't get other errors using pycurl.

What is weird is that it worked without problems before. Since this seems to be a local problem I'd offer to close this Issue!? Thanks for taking your time with this.

**Comment by Fernerkundung** [comment]
Just tested again with the following order of commands. Does anything look different to what you are doing? I'd really like to find out if this is possibly an issue with conda because then we'd need to change the install documentation.

```bash
conda create -n sensat python=2.7
activate sensat
conda install pycurl
pip install sentinelsat
sentinel download <user> <password> 8b0ce6c0-7d59-4014-9a6d-fb917f0e484e
```

**Comment by unnic** [comment]
Except for the `sensat` environment it's the same process I used (as I followed the installation guide)

Following your code (`conda create -n sensat...`) returns the error posted above:
`pycurl.error: (60, 'SSL certificate problem: self signed certificate in certificate chain')` (details in first post)

Using `sentinel download <user> <password> 8b0ce6c0-7d59-4014-9a6d-fb917f0e484e` outside the `sensat` environment generates the faulty .zip:
```
Downloading 8b0ce6c0-7d59-4014-9a6d-fb917f0e484e to .\S2A_OPER_PRD_MSIL1C_PDMC_20160319T130845_R079_V20150807T095007_20150807T095007.zip
   100%    276 Bytes     276 Bytes/s            0:00:00 ETA
```

I'm using Python 2.7 also in my standard environment.
I lack the experience but are you really sure it can be a conda/installation issue if it already worked before? Isn't it more likeley that something in my network or the API changed?

**Comment by Fernerkundung** [comment]
Two last hunches. If it still doesn't work im out of ideas. So far no major changes have been undertaken to the scihub api as well as the sentinelsat code that could break a previous working installation. Either some of your dependencies got messed up during the update or something in your network changed:

Reinstall pycurl in your environment:
```
conda remove pycurl
pip uninstall pycurl
conda install pycurl
```

Try certifi to update your SSL certs:
```
pip install certifi
```

**Comment by unnic** [comment]
It works! Thank you!!

**Comment by unnic** [comment]
ok, it just worked for a short while... I'm back at the broken .zips

**Comment by fradaloisio** [comment]
Can you open the broken .zip? If you can't unzip it, try to rename it in .xml and open it with a text editor. Maybe it is an overquata message. 
Otherwise try to download two product with the same account via browser.

**Comment by Fernerkundung** [comment]
Than the most pressing question is: What did you change inbetween it working and not working?

As @fradaloisio suggested take a look at the zip or upload it to a gist so we can have a look at it. I suspect scihub having some new error messages we didn't account for so far.

**Comment by unnic** [comment]
@fradaloisio bingo. zip as xml reads: `An exception occured while creating a stream : Maximum number of 2 concurrent flows achieved by the user "guest"`

This comes from a _single_ image request: `sentinel download <user> <password> 8b0ce6c0-7d59-4014-9a6d-fb917f0e484e`

Please note that I have sucessfully downloaded >7 Images with a single command using your script in the past.
Just now I requested images for a region for the last month: The first two images found returned the error above, the third is downloading fine right now

> What did you change inbetween it working and not working?

Nothing, not even a restart.

**Comment by Fernerkundung** [comment]
So you are downloading from `https://scihub.copernicus.eu/s2` right now as guest:guest?

Seems like they activated the download limit of 2 concurrent downloads per user for the api where everyone shares the same user.

Should work if you download the scenes from `https://scihub.copernicus.eu/dhus` or, if they are available, `https://scihub.copernicus.eu/apihub`.

Please also take note that we are currently in a [scihub maintencance window](https://scihub.copernicus.eu/news/News00057).

**Comment by fradaloisio** [comment]
From `https://scihub.copernicus.eu/s2/` I can download with guest/guest without any problem.
He downloads from another hub like apihub.

**Comment by unnic** [comment]
I used the default settings up to now. 
`sentinel download guest guest 8b0ce6c0-7d59-4014-9a6d-fb917f0e484e --url https://scihub.copernicus.eu/s2/` works (even in parallel to another running download using your script)

**Comment by Fernerkundung** [comment]
Then I'm stumped. If you are indeed downloading from `dhus` with your own user and password I have absolutely no idea why scihub would report `2 concurrent flows achieved by the user "guest"` unless your username is actually `guest`.

If I start 3 concurrent downloads with my account I can reproduce the issue, otherwise not. Do you happen to share your account with someone else?

**Comment by Fernerkundung** [comment]
Interesting tidbit from the recent SciHub maintenance:

> API Hub user accounts have been updated with SciHub accounts on 22 March 2016.
> Access to API Hub has been now granted to all the users that have registered on Sci Hub before the 22nd of March 2016, 02:00 UTC.
> For these users the same Sci Hub login credentials are valid for accessing API Hub.

Maybe this had something to do with your issue that user "guest" has reached the limit of 2 concurrent downloads. Does the error still persist?

**Comment by unnic** [comment]
Thanks for the info. 

Going via the option `--url https://scihub.copernicus.eu/s2/`  was successfull with a bulk download, albeit one download after another.
