### ISSUE TITLE
Make sentinelsat citeable

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#41]
I'm currently in the process of writing a research paper where I want to quote my use of sentinelsat. The easiest way to do this would be to register releases to DOIs with the help of [Zenodo](https://zenodo.org/). This has become quite popular with scientific software repositories as it bolsters their visibility and makes citing as easy as possible.

There's a [tutorial on the integration of Zenodo and github](https://guides.github.com/activities/citable-code/) which basically sets-up a webhook which archives each release, adds a DOI to the release and allows us to include a badge with the DOI of the current release.

@willemarcel I could set this up myself if you are willing to grant me contributor status (I think I've allready shown that I am commited to this project and would like to keep improving it) or you could set-up the webhook yourself.

**Comment by willemarcel** [comment]
It's done @Fernerkundung! The link to the DOI is in the README. I recognize your commitment to this project, if it was my personal repository sure I would give you write permission, but I can not due to the organization rules.

**Comment by Fernerkundung** [comment]
Thank you very much for making this work. Could you re-check the contributor names at [Zenodo](https://zenodo.org/record/154460) please? They don't look quite right.

**Comment by willemarcel** [comment]
@Fernerkundung What is wrong? I can not edit the authors names, because Zenodo gets everything from github: https://github.com/ibamacsr/sentinelsat/graphs/contributors

**Comment by Fernerkundung** [comment]
@willemarcel Thanks for the link, didn't know they got it all from github directly. That explains my missing last name.
