### ISSUE TITLE
input geojson has to be of type Polygon - fails on type MultiPolygon

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#5]
The input geojson has to contain a geometry of type Polygon. Input with a geometry of type MultiPolygon causes an error.

Ideally I'd expect the search function to loop through all polygons inside the multipolygon geometry, concatenate the results, remove duplicates and return the results for all polygongs at once.

**Comment by willemarcel** [comment]
Of course. The API supports to receive a Line, and maybe a Point object too. But I didn't have time to implement this.

**Comment by Fernerkundung** [comment]
I can try and implement is but the question is rather: is it useful? Or should we just document the behaviour and expect users to split their multipolygons and just run the query for each polygon.

**Comment by citterio** [comment]
Sure it would be a convenient feature for oversize regions like mine. I did not look further into it myself because the large polygon seemed to work - did not even realize it was larger than officially supported.

Btw, today I noticed that the 'max 200 points' is also a bit fuzzy. I have not tried exceeding it, but a 183 points polygon gave an error unless I limit the decimal places in the lat and long to only 2 decimals.

I created a [wiki page] (https://github.com/ibamacsr/sentinelsat/wiki/SciHub-notes) to keep notes of undocumented things like these (as well as exceptions occurring when SchiHub is in maintenance, as suggested in #4)

**Comment by jamesemwheeler** [comment]
Great utility, so useful for what I'm doing right now. Thanks!

This is my python workaround for a single multipolygon geojson input with multiple geojson outputs for each feature (apologies for messiness and indenting issues, I'm not used to python or even this website):

import sentinelsat
#you need to install json module
import json
from sentinelsat import sentinel
from sentinelsat.sentinel import SentinelAPI
api = SentinelAPI('user', 'password', 'https://scihub.copernicus.eu/dhus')

with open('/path/filename.geojson') as f:
    data = json.load(f)

#loop through each feature (polygon)
for feature in data['features']:
    #Parse geojson into the format used by the sentinel query tool - extreme messiness here!
    coords=feature['geometry']['coordinates']
    coords=str(coords)
    coords2=coords.replace("[[","")
    coords2=coords2.replace("]]","")
    coords2=coords2.replace(",","")
    coords2=coords2.replace(" [",", [")
    coords2=coords2.replace("[","")
    coords2=coords2.replace("]","")
    #I was querying over landsat tile footprints
    path=feature['properties']['PATH']
    row=feature['properties']['ROW']
    #query sentinel data at the polygon location (intersection)
    api.query(coords2, '20140430', '20160405', platformname='Sentinel-1', producttype="GRD")
    #make output filename
    filename="/output_path/output_name_"+str(path)+"_"+str(row)+".geojson" 
    file = open(filename, "w")
    x=str(api.get_footprints())
    file.write(x)
    file.close()
    #uncomment below for download
    #api.download_all()

**Comment by Fernerkundung** [comment]
There allready is a functionality in place that let's you select which polygon you want to use in case of a multipolygon. I forgot to document it so far - I'll change that.

`get_coordinates(geojson_file, feature_number=0)`

When you know your number of features are, say `10` you can do:

```python
api = SentinelAPI('user', 'password', 'https://scihub.copernicus.eu/dhus')

num_features = 10  # or maybe take directly from GeoJSON FeatureCollection

for i in num_features:
     api.query(get_coordinates(filename.geojson, i),
                     '20140430', '20160405',
                     platformname='Sentinel-1', producttype="GRD")
```

This way you don't have to parse the GeoJSON yourself (except for the WRS2 Path/Row names). I'd also suggest you take a look at the [GeoJSON python library](https://github.com/frewsxcv/python-geojson) to do that - which makes parsing a lot easier.

**Comment by jamesemwheeler** [comment]
That's great, thanks. Much tidier than my workaround.
(I'm pretty new to this, next time I'll use the insert code button)

**Comment by Fernerkundung** [comment]
Don't worry about it, we can still see what you were getting at. Feel free to report issues you find or contribute any way you can.

**Comment by Fernerkundung** [comment]
Closing this since the failure on MultiPolygons has been resolved.

**Comment by Fernerkundung** [comment]
Documented: http://sentinelsat.readthedocs.org/en/latest/api.html#sentinelsat.sentinel.get_coordinates
