### ISSUE TITLE
Error: Maximum number of 2 concurrent flows achieved

### ISSUE THREAD

**Issue by unnic** [ibamacsr/sentinelsat#51]
Hello,

when I try to download a series of images for a region the resulting download is a .zip file with 1kb. Opening with a text editor reveals:
`<?xml version='1.0' encoding='UTF-8'?><error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><code/><message xml:lang="en">An exception occured while creating a stream : Maximum number of 2 concurrent flows achieved by the user "[user]"</message></error>`

It's the only download running from this user.
Any ideas?

**Comment by Fernerkundung** [comment]
Are you downloading with one sentinelsat instance or multiple at once?

**Comment by unnic** [comment]
one instance

**Comment by Fernerkundung** [comment]
Currently having similar performance issues with SciHub. My guess is this is related to them changing the product format to [distribute Sentinel-2 data in grid tiles](https://scihub.copernicus.eu/news/News00102).
