### ISSUE TITLE
Sentinel-3 support

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#54]
This issue is supposed to be a starting point of discussion for Sentinel-3 support. As of 2016-10-20 [Sentinel-3 images are published on Scihub](https://scihub.copernicus.eu/news/News00109).
- [x]  include `--sentinel3` flag in CLI?
- [x] expose selection of [all Sentinel-3 instruments](https://sentinel.esa.int/web/sentinel/missions/sentinel-3/instrument-payload) in CLI/API or focus on OLCI?
- [x] does Sentinel-3 come with new search keywords? (cloud cover, etc.)
- [x] Do search&download work or need to be refactored?
- [x] Include tests once Sentinel-3 products leave pre-ops phase and are published on `apihub`

**Comment by Fernerkundung** [comment]
@valgur @willemarcel @j08lue 

Do you think a `--sentinel3` flag would be usefull? This would return results from the OLCI, SLSTR and SRA instruments. Most users need only one of those products, which could be dealt with `-q 'instrumentshortname=SLSTR'`.

This becomes a more general question: Do we try to expose all instruments/products with flags in the CLI or do we expand the documentation with examples so users can use the `-q` flag to construct the query?

I got most of the Sentinel-3 support working with a simple change to the [`to_dict` parsing](https://github.com/Fernerkundung/sentinelsat/commit/ba3139e5c298a4fc2dd762c85177a3f9cf517353) due to a new item identifying collections as `{'name: 'collection, 'str':'002}` instead of ``{'name: 'collection, 'content':'002}``

**Comment by valgur** [comment]
It would make sense to me to extend the CLI with `--sentinel3` and `--instrument=XXX` parameters. We should obviously strive to cover the most common query parameters (the instrument, location, date and cloud cover percentage, as far as I'm aware) in the CLI for less typing as well as for the convenience of not having to look up the relevant parameters in the SciHub API docs. Creating a separate parameter for each instrument seems excessive for me though. We can just list all of the relevant ones in the `--instrument` parameter info.

Thanks for fixing the `to_dict`, good job!

**Comment by willemarcel** [comment]
I also agree with the `--sentinel` and `--instrument`!

**Comment by Fernerkundung** [comment]
Good suggestions @valgur 

I propose to go forward as follows:

-[ ] deprecate `--sentinel1` and `--sentinel2` (with message) and remove them with the next major release
-[ ] add new `--sentinel <int>` flag that allows selection by `platformname`
-[ ] add new `--product <str>` flag that allows selection by `producttype` (e.g. SLC, GRD) 
-[ ] add new `--instrument <str>` flag that allows selection by `instrumentname` (this is geared towards Sentinel-3 OLCI/SRAL/SLSTR etc.

This includes a bit of redundancy but should cover most use cases and the most relevant query parameters.

**Comment by Fernerkundung** [comment]
Done with #109
