### ISSUE TITLE
OpenSearch limits number of rows

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#57]
Bad [news from ESA](https://scihub.copernicus.eu/news/News00111):

>many scripts using the OpenSearch API have been attempting to retrieve extremely large numbers of results from queries via use of the OpenSearch ‘rows' parameter. A new behaviour has been implemented in the data hub software to protect for this and allow a maximum number of rows to be returned in a single query, set at 100 for the moment.

At the moment we query [up to 1500 rows](https://github.com/ibamacsr/sentinelsat/blob/0ed829b211811cf16898acd7c6726bfb853b24cd/sentinelsat/sentinel.py#L132). Meaning we will get `HTTP Error 500` all the time.

To absolve this a new logic is required that iteratively queries the Scihub for results 1-100, 101-200, 201-300, etc. until no more results are returned.

Fortunately this can be done with the OpenSearch `step` parameter:
>Results sets over the maximum can be obtained through paging of from different start values via use of the OpenSearch 'start' parameter.

**Comment by j08lue** [comment]
Are you working on this already, @Fernerkundung? Else I could help.

**Comment by Fernerkundung** [comment]
I won't be able to tackle this for the next two weeks. Would be great if you could chime in @j08lue.

**Comment by Fernerkundung** [comment]
Solved with #60
