### ISSUE TITLE
Downloading 1 KB files.

### ISSUE THREAD

**Issue by andrejreznik** [ibamacsr/sentinelsat#62]
Sometimes I got this problem. When I downloading products for date range I see that size of some files is 1KB (mean zero bytes). Like on this screenshot. 
![screen shot 2016-10-31 at 1 09 34 pm](https://cloud.githubusercontent.com/assets/15221530/19852329/5e01b05c-9f6b-11e6-850b-368b9a0ae3d6.png)

**Comment by Fernerkundung** [comment]
Is it allways the same files or do they change after a second download attempt (which skips all the finished files)?

**Comment by andrejreznik** [comment]
@Fernerkundung 
> Is it allways the same files or do they change after a second download attempt
Not same. Just random files. If I delete and try to download again the files are downloading ok.
> Sentinelsat version 0.7.1?
Yeah, last version (upgrade by pip)

**Comment by andrejreznik** [comment]
Here 2nd try download. As you can see 3 of 4 file are download now correctly and 1 failed again. Only when I delete this file and start download 3rd time the file is downloaded correctly.
![screen shot 2016-10-31 at 2 33 19 pm](https://cloud.githubusercontent.com/assets/15221530/19854387/5d55d37a-9f77-11e6-879a-72737d93e3de.png)

**Comment by unnic** [comment]
Try to open the 1kb files with a text editor. I usually find an error message within such files.

**Comment by jens2121** [comment]
I am experiencing a similar problem. I am busy downloading Sentinel 2 data and the of the 30 items that are meant to download, only 12 have successfully downloaded and the remaining files are 1kb files. I can't extract or open them in the text editor. (download was done using the CLI)

**Comment by valgur** [comment]
You should try adding `--md5` to the command line arguments if you haven't. It makes the script check the file's integrity and restart the download, if it's corrupt.

**Comment by jens2121** [comment]
@valgur thank you this seems to resolve the issue I had!
