### ISSUE TITLE
Revert some changes to SentinelAPI from last PR

### ISSUE THREAD

**Issue by j08lue** [ibamacsr/sentinelsat#63]
@valgur, in the last PR, there were a few changes to `SentinelAPI` you wanted to revert. I think [you made good points](https://github.com/ibamacsr/sentinelsat/pull/60#issuecomment-256920814), so here they are for further discussion:

> 2. I would rename the <code>max_query</code> to <code>page_size</code> (since we are doing pagination) and change the <code>max_query</code> to actually limit the number of items returned. Again, to reduce stress on the SciHub server if we actually do just need a limited number of query results.</li>
> 4. I preferred the <code>query_raw()</code> over <code>load_query()</code> which sounds too similar and redundant to <code>query()</code> to me. Could be named something else as well, but either way, I think a function that exposes the text-search format of the SciHub server should be a first-class citizen in the API, since it is much more powerful, if necessary, than the main <code>query()</code> function. For example, it allows for any logical statements that include <code>OR</code> and parentheses to be used. I also occasionally find <code>footprint:Contains()</code> to be useful instead of <code>footprint:Intersects()</code>. I have been intending to add the raw text query support to the CLI as well but have not found time for that yet. </li>

**Comment by Fernerkundung** [comment]
+1 on both:

2. could be usefull to implement something like 'sentinel search ... -head 10' or 'tail' if someone wants to see some results of the queried area without limiting the query too much. I find myself sometimes to expand the time window unnecessarily and then just looking at the first 5 scenes returned.

3. Never used queries in that way but I do see the added value of this. Adds flexibility for power users without limiting the ease of use for anyone else.

**Comment by j08lue** [comment]
I just went about implementing `1.` but got stuck on how to implement the `head`/`tail` or `max_query` limit. 

We could execute the full query and then only return the subset the user asks for. If we go ahead with #65, this will be very straightforward: The user anyways gets the full list of products from the query and can do with it what she wants - subset, filter... The same we could do in the CLI with `head`/`tail` options.

If we want to limit the actual query/page iterations with `max_query`, things get more complicated. What if `max_query` is not a multiple of `page_size`? Should we load the full last page and then still limit the returned number of points? I found that this adds a lot of code to the API functions.

We could also expose `start_row` as an argument to `query`, then savvy users could choose e.g. to start the query on page 3 in steps of 10 rows (getting the `tail` of the products).

But I suggest we just leave out the `max_query` part on the API and maybe add the `head`/`tail` options to the CLI, hoping that users don't get lazy and query a whole year only to get the latest 5 products. :-)

**Comment by j08lue** [comment]
@valgur, is `2.` actually just about the name, or was [`query_raw`](https://github.com/ibamacsr/sentinelsat/blob/0ed829b211811cf16898acd7c6726bfb853b24cd/sentinelsat/sentinel.py#L141-L147) functionally different from [`load_query`](https://github.com/ibamacsr/sentinelsat/blob/9d6736511fecda6f5c884bb53af74954957330e0/sentinelsat/sentinel.py#L146)?

If I understand it correctly, you can do what you ask for (post custom query strings) with `load_query` also, right? I am happy to rename it back to `query_raw`, if that is it.

**Comment by Fernerkundung** [comment]
`head` and `tail` are just 'nice to haves' but I doubt they are often relevant to users. As you said, if we give users the full product list they are free to filter/change/list them how they want.

`head` I can see as easily implemented with the existing code if `max_rows` is simply set to 10. `tail` is another beast entirely. As you said we would need to know the exact number of results prior to returning only the last ones. This won't reduce the server load at all - so best if we scrap them and/or just implement them as 'filter functions' to the list of returned results.

While it is good practice to try and keep the load on ESAs servers minimal I don't think that should stand in the way of the programm design too much.

**Comment by jamesemwheeler** [comment]
Hi, I think my problem below might be related to this thread:

I'm using sentinelsat to produce Sentinel 1 footprint coverage from a multi-polygon geojson. Each query command I run contains the results of the previous one, even though not all queries exceed 100 total results. I'm not using this library to download imagery from the scihub data repository so (I imagine) there shouldn't be an issue with overloading their servers.

It's either a problem with my code (below), the apihub servers holding my query (does that happen?), or the latest update to the query/load_query function. As you can probably see I'm not really equipped to alter your original code. If other people are reporting this perhaps it would be worth finding out what's happening.

Regards,

James

Sample code below - apologies for messiness.


```
import sentinelsat
import json

from sentinelsat import sentinel
from sentinelsat.sentinel import SentinelAPI

#user name, password and website of S1 and S2 information/data
api = SentinelAPI('user', 'password', 'https://scihub.copernicus.eu/apihub')

#5 degree tiles in geojson format
geojsonfile = '/home/user/Data/Africa_Sentinel_Tiles/Africa_SFD_grid_5.geojson'

#designated output folder
output_folder = '/home/user/Data/Africa_Sentinel_Tiles/Sentinel_SFD_GRIDS/Five_degree/'
final_output_folder = '/home/user/Data/Africa_Sentinel_Tiles/Sentinel_SFD_GRIDS/Five_degree/Downloads/'
if not os.path.exists(final_output_folder):
    os.makedirs(final_output_folder)
#read tile geojson and calculate number of features
with open(geojsonfile) as f:
    data = json.load(f)

num_features = len(data['features'])

#download and write geojsons containing Sentinel1 footprints for each of the tiles from copernicus apihub
for i in range(0,num_features):
    api.query(get_coordinates(geojsonfile,i),'20150731','20160731',platformname='Sentinel-1',producttype="SLC",sensoroperationalmode="IW")
    print(i)

    tile1 = data['features'][i]['properties']['xmin']
    tile2 = data['features'][i]['properties']['ymax']
    filename=output_folder+"Africa_Sentinel1_SLC_IW_20150731_20160731_TILE_"+str(tile1)+"_"+str(tile2)+".geojson"
    file = open(filename, "w")
    x=str(api.get_footprints())
    file.write(x)
    file.close()

```

**Comment by j08lue** [comment]
@jamesemwheeler thanks for your report.

This is actually much more related to #65 (statefulness): Every call to `api.query` **appends** the newly found products to the `api.products` attribute (which is a `list`). So that list is never flushed.

To avoid that and start with a fresh list every time, call `api.products = []` at the bottom of your loop (inside the loop) or before your call to `api.query`.

But you are right, this behaviour was introduced with the PR this thread refers to. Perhaps we should consider reverting that. But then there is #65, which will solve this problem and make it more clear what is happening.

**Comment by jamesemwheeler** [comment]
@j08lue  Thank you very much for your response, I have tried that and it works. I will repost my first post and your response in #65 

James

**Comment by j08lue** [comment]
What remains of this issue are considerations about extra options for query subsetting but I think [we agreed](https://github.com/ibamacsr/sentinelsat/issues/63#issuecomment-258683955) that these are superfluous. Closing this.
