### ISSUE TITLE
Reduce statefulness of `SentinelAPI`

### ISSUE THREAD

**Issue by j08lue** [ibamacsr/sentinelsat#65]
This is also a discussion from PR #60.

Currently, `api.query` stores the results in the `api.products` attribute, which `api.download_all` subsequently accesses. I agree with @valgur in [his comment](https://github.com/ibamacsr/sentinelsat/pull/60#issuecomment-256920814) that this feels like a bad design choice, because the state of the `SentinelAPI` instance becomes very important for the whole flow `query > download`. What if we want to perform another query with the same API instance, while a download is in progress? Would this alter the list that the `download_all` routine is at the same time iterating over?

A solution would be to have `query` return the results and the user pass them to `download_all`. Another benefit of this solution would be that it becomes cleaner to filter the query results before downloading. For example, if I want to download my products grouped by date, I currently have to modify the `api.products` list before calling `download_all` but keep the original list.

A change is easy to implement but changes the way users have to deal with the API. Any opinions on whether we should pull this through?

**Comment by willemarcel** [comment]
@valgur @j08lue I agree that we can add another argument to `download_all` so we could define what we want to download with more flexibility. Remember that the Sentinel API is very restricted in terms of parallel downloads and queries. I prefer to avoid executing two actions at the same time.

**Comment by Fernerkundung** [comment]
I'm a firm +1 on the ability to being able to filter the results of `query` before passing them on to `download_all`. 

@willemarcel is right that we should not allow more than two interactions with the SciHub at the same time. ESA states, that it limits the dowloads to two concurrent but I found that 3 simultaneous searches result in random errors as well. So any filtering of the `products` should preferrably happen without initiating new queries.

**Comment by jamesemwheeler** [comment]
Reposting relevant post and response from me and @j08lue from #63:

> I'm using sentinelsat to produce Sentinel 1 footprint coverage from a multi-polygon geojson. Each query command I run contains the results of the previous one, even though not all queries exceed 100 total results. I'm not using this library to download imagery from the scihub data repository so (I imagine) there shouldn't be an issue with overloading their servers.
> 
> It's either a problem with my code (below), the apihub servers holding my query (does that happen?), or the latest update to the query/load_query function. As you can probably see I'm not really equipped to alter your original code. If other people are reporting this perhaps it would be worth finding out what's happening.
> 
> Regards,
> 
> James
> 
> Sample code below - apologies for messiness.
> 
> ```
> import sentinelsat
> import json
> 
> from sentinelsat import sentinel
> from sentinelsat.sentinel import SentinelAPI
> 
> #user name, password and website of S1 and S2 information/data
> api = SentinelAPI('user', 'password', 'https://scihub.copernicus.eu/apihub')
> 
> #5 degree tiles in geojson format
> geojsonfile = '/home/user/Data/Africa_Sentinel_Tiles/Africa_SFD_grid_5.geojson'
> 
> #designated output folder
> output_folder = '/home/user/Data/Africa_Sentinel_Tiles/Sentinel_SFD_GRIDS/Five_degree/'
> final_output_folder = '/home/user/Data/Africa_Sentinel_Tiles/Sentinel_SFD_GRIDS/Five_degree/Downloads/'
> if not os.path.exists(final_output_folder):
>     os.makedirs(final_output_folder)
> #read tile geojson and calculate number of features
> with open(geojsonfile) as f:
>     data = json.load(f)
> 
> num_features = len(data['features'])
> 
> #download and write geojsons containing Sentinel1 footprints for each of the tiles from copernicus apihub
> for i in range(0,num_features):
>     api.query(get_coordinates(geojsonfile,i),'20150731','20160731',platformname='Sentinel-1',producttype="SLC",sensoroperationalmode="IW")
>     print(i)
> 
>     tile1 = data['features'][i]['properties']['xmin']
>     tile2 = data['features'][i]['properties']['ymax']
>     filename=output_folder+"Africa_Sentinel1_SLC_IW_20150731_20160731_TILE_"+str(tile1)+"_"+str(tile2)+".geojson"
>     file = open(filename, "w")
>     x=str(api.get_footprints())
>     file.write(x)
>     file.close()
> 
> ```

@jamesemwheeler thanks for your report.

This is actually much more related to #65 (statefulness): Every call to `api.query` **appends** the newly found products to the `api.products` attribute (which is a `list`). So that list is never flushed.

To avoid that and start with a fresh list every time, call `api.products = []` at the bottom of your loop (inside the loop) or before your call to `api.query`.

But you are right, this behaviour was introduced with the PR this thread refers to. Perhaps we should consider reverting that. But then there is #65, which will solve this problem and make it more clear what is happening.

**Comment by lucadelu** [comment]
Hi,

I started to work on this issues with this commit 7328b45, I removed self.products, `query` is now returning a list of products and this list can be passed to `download_all`, `get_footprints`, `get_products_size` functions. 

Let me know if you like this solution

**Comment by j08lue** [comment]
Good work, @lucadelu . So this is already in `master` now? It will break some people's scripts for sure, so maybe we should announce this somehow...

**Comment by lucadelu** [comment]
@j08lue no is only on my branch `products`. It is an API change so I would have some feedback before end my work. I have to update tests and REAME for sure, something else to check?

If the are no objections I will finish this work on Monday and I will submit new pull request.

**Comment by j08lue** [comment]
Somehow I was not able to see where that commit lived. 

Perhaps you should already open a PR, then we can discuss possible adjustments there. You can always add more commits to that PR.

**Comment by lucadelu** [comment]
Done in #81

**Comment by j08lue** [comment]
Fixed with #81.
