### ISSUE TITLE
Broken functionality due to SciHub upgrade

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#8]
Since 08.10.2015 ESA is [preparing the SciHub for Sentinel-2](https://scihub.esa.int/news/News00037) distribution. During this they upgraded the datahub software and changed the format of the query returns.

This broke for instance the `get_footprints` method. I am working on a fix for that and just wait for the dhus to come back online so I can test it before creating a PR.

Anyone else found broken functionality that requires refactoring?

Regarding Sentinel-*2*:
 should sentinelsat be able to download Sentinel-2 as well once it is available? I don't think it would require a lot of refactoring. How would this best be included in the CLI - a separate option, like `--satellite` or `--sensor` or document how to use the query with `-q` for that?

**Comment by willemarcel** [comment]
I don't found anything else broken. I think we should support Sentinel-2 as well, an option like you suggested is good.

**Comment by Fernerkundung** [comment]
Footprints fixed with  #9 

ESA finished the SciHub upgrades but still no word on Sentinel-2 data delivery.
