### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by Fernerkundung** [ibamacsr/sentinelsat#92]
With API breaking changes (as introduced in v0.8) I think it is high time we create a changelog. I propose one in the style of [keepachangelog.com](http://keepachangelog.com/en/0.3.0/).

I started working on one here: [942d920](https://github.com/Fernerkundung/sentinelsat/commit/a932f7674c9ba643fbc74e4aad7405aece570d97). I'm currently trying to propagate it based on historic PRs and commit messages - so the first iteration will need some review.

New PRs should add their changes into an 'Unrealeased' section, which allows maintainers to just change the version number w/o having to writing the changelog - anyone creating a PR probably knows best what they changed/broke/fixed.

Proposed layout is:

### Added
- for new features.
### Changed
- for changes in existing functionality.
### Deprecated
- for once-stable features removed in upcoming releases.
### Removed
- for deprecated features removed in this release.
### Fixed
- for any bug fixes.
### Security
- to invite users to upgrade in case of vulnerabilities.

**Comment by lucadelu** [comment]
I like the proposal to add a CHANGELOG file it is really useful

do you want also to cover previous release or only from the next ones?

**Comment by Fernerkundung** [comment]
@lucadelu I am trying to include previous releases as well - but it's quite trickly to puzzle everything together from PRs and commit messages.

**Comment by Fernerkundung** [comment]
Closed with release of v0.8.1
